blueprint:
  name: Externer Temperatursensor f체r Thermostatsteuerung
  description: Steuert das Thermostat basierend auf der Temperatur eines externen Sensors.
  domain: automation
  input:
    thermostat:
      name: Thermostat
      description: Das zu steuernde Thermostat
      selector:
        entity:
          domain: climate
    temperature_sensor:
      name: Externer Temperatursensor
      description: Sensor, der die Referenztemperatur liefert
      selector:
        entity:
          domain: sensor
          device_class: temperature
    target_temperature:
      name: Zieltemperatur
      description: Zieltemperatur f체r den Raum, basierend auf dem externen Sensor
      selector:
        number:
          min: 10
          max: 30
          unit_of_measurement: "째C"
          step: 0.5
    tolerance:
      name: Temperaturtoleranz
      description: Die Schwelle, bei der das Thermostat angepasst wird
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1
    schedule:
      name: Zeitplan (optional)
      description: Aktiviere diese Steuerung nur w채hrend bestimmter Zeiten
      default: []
      selector:
        time:
          mode: list

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input temperature_sensor

condition:
  - condition: template
    value_template: >
      {% if input.schedule | length > 0 %}
        {% set current_time = now().strftime('%H:%M') %}
        {% for time in input.schedule %}
          {% if time == current_time %}
            true
          {% endif %}
        {% endfor %}
      {% else %}
        true
      {% endif %}

action:
  - variables:
      current_temperature: "{{ states(input.temperature_sensor) | float }}"
      target_temperature: "{{ input.target_temperature | float }}"
      tolerance: "{{ input.tolerance | float }}"
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ current_temperature < target_temperature - tolerance }}
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat
            data:
              temperature: "{{ target_temperature }}"
      - conditions:
          - condition: template
            value_template: >
              {{ current_temperature > target_temperature + tolerance }}
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat
            data:
              temperature: "{{ target_temperature - 1 }}"
